### ISSUE TITLE
Describe whether the service is free or not and how long it will stay around

### ISSUE THREAD

**Issue by roryokane** [tibdex/autorebase#10]
I know that right now, this GitHub app is free, and at the current level of use it is very cheap to run on Microsoft Lambda.

After you have done calculations based on your expected level of use, you should write in the README some promises or explicit non-promises about whether this app will cost money and whether it will stay running. You can also assure users that even if the hosted GitHub app shut down, they could host it themselves, use an alternative, or go back to running Git commands manually.

**Comment by tibdex** [comment]
Thanks for creating the issue.

I updated the description [here](https://github.com/apps/autorebase). Do you like it?
