### ISSUE TITLE
Clarify how / why labels are added or removed

### ISSUE THREAD

**Issue by ronnix** [tibdex/autorebase#38]
Hi,

We've been trying the autorebase bot but witnessing some behaviour that's not clear to us.

When we add the `autorebase` label to a PR, the bot will rebase the branch when it gets out of date, and then sometimes remove the label. Is this by design?

We've also seen the bot remove the label, rebase the branch, then add the label again. Not sure why it's doing this!
![screen shot 2019-01-28 at 15 23 09](https://user-images.githubusercontent.com/321872/51842248-bc78e800-2310-11e9-9d26-2f8ae6b23f52.png)

**Comment by tibdex** [comment]
Hi Ronan,

David is right, it's to avoid concurrent rebases. I'll move the comment to the readme :)

**Comment by ronnix** [comment]
Got it, thanks!
