### ISSUE TITLE
Adding the label does not trigger autorebase

### ISSUE THREAD

**Issue by ebsaral** [tibdex/autorebase#40]
I installed the app, and gave permission to our private repo. But when I add the label `autorebase`, it doesn't trigger the bot. I am able to see the bot `autorebase` in the author list. Should we do something additional like adding the webhook manually? 

Another thing is that our target branch is `staging`, not `master`. Does this cause the problem?

**Comment by tibdex** [comment]
Hi Emin,

Installing the app and enabling it on a repo is all you need to do. However, PRs labeled with `autorebase` won't be rebased if they have failing status checks as [explained in the README](https://github.com/tibdex/autorebase#usage). Where you expecting another behavior? If yes, which one?

**Comment by ebsaral** [comment]
Hi @tibdex ,

I read the readme and like you said, it's green but still it does not work. Is there a specific order about when to add the label? Please check the screenshot I took. I have to mention again that it's a private repo. I can't think of a proper reason why it shouldn't work. :/ I would really love to use this app.

![screen shot 2019-02-19 at 9 28 56 am](https://user-images.githubusercontent.com/2864828/53000711-45bf9e00-3429-11e9-94b6-6343c1f13ca1.png)

![screen shot 2019-02-19 at 9 34 00 am](https://user-images.githubusercontent.com/2864828/53000823-84555880-3429-11e9-8c2c-aeae2fe87c12.png)

**Comment by tibdex** [comment]
The app is working fine for me and other projects are using it without issues. I don't have access to the logs of last week. Could you try again and tell me about it so that I can look into the GitHub webhooks sent and the logs on Zeit's Now?

**Comment by ebsaral** [comment]
Hey. I have just seen your message, and applied the label immediately right now. I would be happy if you could check the logs. Thank you!

![screen shot 2019-02-25 at 11 25 42 am](https://user-images.githubusercontent.com/2864828/53330986-25dc1e80-38f0-11e9-8c50-6d291f80814f.png)

**Comment by tibdex** [comment]
I checked and GitHub indeed sent a webhook following your label addition. So this means the app is correctly installed on your repo.
However, I tried to do a dry-run of Autorebase on your PR but it's now closed/merged. Can you please open a dummy PR on the same repo, put it in a green/mergeable state, add the `autorebase` label, tell me when it's done, and keep it open. I'll then do another dry-run and try to gather more information. My suspicion is that GitHub would see your PR's [mergeableStateStatus](https://developer.github.com/v4/enum/mergestatestatus/#behind) as different from `clean`/`behind`.

**Comment by ebsaral** [comment]
I believe the issue comes from the branch protection settings. When I remove the protection on the branch, autorebase worked successfully.

![screen shot 2019-02-26 at 06 18 26](https://user-images.githubusercontent.com/2864828/53389195-ad786a80-398e-11e9-8c23-a5cc98ee0c3b.png)

Do we have to reconfigure the settings or do you have any suggestion to give permission to autorebase app?

**Comment by tibdex** [comment]
Hi Emin,

Autorebase will need push permission on the head branch of the PR to be able to rebase it and on its base branch to be able to merge it. I don’t know if you can add Autorebase to the list of “people and teams with puss access” visible in your screenshot.

I usually never use this “restrict who can push to matching branches” setting and prefer to require pull requests to be approved by a “code owner” reviewer instead. Maybe you could try that too.

**Comment by tibdex** [comment]
Did you manage to make it work?
