### ISSUE TITLE
Optional rebase + merge --no-ff

### ISSUE THREAD

**Issue by gaizka** [tibdex/autorebase#46]
Hi!

First of all, thanks a lot for autorebase, it is a really useful project.

Would it be possible to configure autorebase to change its final rebase behaviour?

Now, when a PR has the "autorebase" tag, and the build status is green, autorebase merges the PR with the github api by using the rebase method.

I would like autorebase to do something like: `git  rebase + git merge --no-ff`, to get something like this git history:

![1-nonlinear-vs-linear](https://user-images.githubusercontent.com/25550/57290011-d74fbb00-70bc-11e9-87eb-cff41f91565d.png)

I have tried changing `autorebase.ts` to:
```
  await octokit.pulls.merge({
    merge_method: "merge",
```

and it does work, to some extend. autorebase merges the PR when the build is green, but it does not make a rebase first. It does not "detect" that the master branch has evolved and that before merging it should make another rebase.

Would it be possible to make something like this? I am not fluent at all at typescript, but if you give me some hints about what would be needed I can try to develop it.

Thanks a lot!!

**Comment by tibdex** [comment]
Hi,

What would be the benefit of using `merge_method: 'merge'`? What do you don't like about rebase method? Have you read [this section of the readme](https://github.com/tibdex/autorebase#why-rebasing-instead-of-squashingmerging)?

**Comment by robwise** [comment]
The advantage is being able to see branch history/PRs explicitly in your Git history. If you're doing rebase merges, you can't tell where one branch or spike ended and the next one started when looking at the git history. You can only reverse engineer this by looking up some of the commits on GitHub and finding the associated PR, which is a bit clunky.

This is an example (sorry for redactions, don't want to breach my company's security policy). You can clearly see in the Git history where the original branch was and what PR it was without even needing to go to GitHub at all. We still rebase though, so it's always in this extremely simple linear history the OP was talking about:

![](https://cl.ly/56a48d71576e/%255Bfeb8e23727ccc812d154428fad458db9%255D_Image%2525202019-06-21%252520at%2525201.00.02%252520PM.png)

**Comment by asbjornu** [comment]
I also vehemently detest squashes and want full Git history in feature branches when they are merged. All I want is a bot to perform a `git rebase develop` so feature branches are up to date and tested before merging. Since it's only possible to do a merge-update on a PR branch in GitHub's UI (see isaacs/github#88), you'd think autorebase would be the perfect solution to this problem.

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
