### ISSUE TITLE
Rebase failed: Not Found

### ISSUE THREAD

**Issue by thedrow** [tibdex/autorebase#48]
See https://github.com/celery/celery/pull/5529#issuecomment-500335075.
It's not very clear from the error what went wrong exactly.

**Comment by tibdex** [comment]
Hi Omer, indeed that's a bad error message. The root cause is that Autorebase doesn't work with forks. See https://github.com/tibdex/autorebase/issues/43.

It would be good to at least make the error handling better when Autorebase faces PRs coming from forks.

**Comment by thedrow** [comment]
I just commented on that issue.

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
