### ISSUE TITLE
Merge strategies: How to squash'n'merge by default but also allow rebase

### ISSUE THREAD

**Issue by karfau** [tibdex/autorebase#50]
Thx for offering this service and github app!

Although I scanned the Readme multiple times it is not clear to me how to support the following use case:
We switched off merging PRs but we let developer pick to squash'n'merge or rebase. The common default is squash'n'merge, but adding the `autorebase` label always rebases.
How to let the app know that for this specific PR I want it to be squash'n'merged?
Could that be done with another label `autosquash`?
Or can something be configured or are there more comment options?

I hope I was able to phrase my question n an understandable manner.

Best Christian

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
