### ISSUE TITLE
When autorebase does it's job, development status in Jira is outdated for a while

### ISSUE THREAD

**Issue by karfau** [tibdex/autorebase#51]
It could of course also be an issue with Jira, but are there any webhooksnot triggered that would be triggered when landing something by clickng the buttons?

With that information I would cross post the issue for Jira (cloud) and cross link the two issues.

Thx in advance

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
