### ISSUE TITLE
Missing instructions for running tests

### ISSUE THREAD

**Issue by Nr9** [tibdex/autorebase#52]
I'm trying to deploy autorebase for my organisation. I trying to configure the CI for the project.

I'm having trouble executing the test locally. I figured mostly everything that goes in the `.env`, but always end up with the following error: `HttpError: Resource not accessible by integration
`

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
