### ISSUE TITLE
Github Rate Limit

### ISSUE THREAD

**Issue by Nr9** [tibdex/autorebase#53]
I deployed the autorebase app on Zeit. 

I receive multiple error concerning GitHub Rate Limit: `HttpError: API rate limit exceeded for installation ID XXXX`. I'm unsure what steps I need to take to resolve this problem.

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this project anymore](https://github.com/tibdex/autorebase/blob/4de07e27937b3311bba661e816be7e379e54a5b9/README.md#maintenance-update).
