### ISSUE TITLE
Public instance down

### ISSUE THREAD

**Issue by tibdex** [tibdex/autorebase#55]
The [public instance](https://github.com/apps/autorebase) has been shutdown:
- It went way over the [Zeit Free Plan](https://zeit.co/pricing).
- Focus has shifted to the development of [Autosquash](https://github.com/marketplace/actions/autosquash), the successor of Autorebase. More explanation [here](https://github.com/tibdex/autorebase/tree/4de07e27937b3311bba661e816be7e379e54a5b9#maintenance-update).

**Comment by mikeparker** [comment]
Does this mean the bot will no longer work? We were considering using it - would be great to know if it doesnt work!

(We are sticking with the rebase strategy so we don't want squash+merge)

**Comment by tibdex** [comment]
It means you need to host it yourself and create your own GitHub app if you want to use Autorebase. You can then reuse these commands to deploy it on Zeit:

https://github.com/tibdex/autorebase/blob/3ea4cc54eb5ec15f4668402208bb4bc49c51838d/.circleci/config.yml#L26-L30

Or you could deploy it elsewhere with your own script.

**Comment by mikeparker** [comment]
Ok great, thanks!
